const defaultHighlights = (title) => [
  `Guided sightseeing of top attractions in ${title}`,
  "Comfortable 3-star deluxe hotel stays",
  "Daily breakfast and dinner included",
  "AC vehicle transfers and sightseeing",
  "Dedicated tour manager assistance",
];

const defaultInclusions = [
  "Accommodation in deluxe hotels / resorts",
  "Daily breakfast and dinner",
  "All transfers and sightseeing in AC vehicle",
  "Tour manager assistance throughout the trip",
  "Toll, parking, and driver allowances",
];

const defaultExclusions = [
  "Flight / train tickets unless mentioned in package note",
  "Personal expenses (laundry, tips, phone calls)",
  "Optional adventure activities and entry fees",
  "GST / government taxes if applicable",
  "Anything not mentioned in inclusions",
];

const enrich = (pkg) => ({
  ...pkg,
  destination: pkg.destination || pkg.title.replace(/\s+Tour$/i, "").trim(),
  duration: pkg.duration || "7 Days / 6 Nights",
  highlights: pkg.highlights || defaultHighlights(pkg.title),
  inclusions: pkg.inclusions || defaultInclusions,
  exclusions: pkg.exclusions || [
    pkg.note || "Flight / train tickets extra",
    ...defaultExclusions.slice(1),
  ],
  available: pkg.available !== undefined ? pkg.available : true,
});

export const seedPackages = [
  enrich({
    title: "Leh Ladakh Tour",
    destination: "Leh Ladakh",
    date: "11 AUG - 17 AUG",
    year: 2026,
    price: 30500,
    note: "Flight tickets extra",
    type: "Domestic",
    category: "September - December 2026",
    image: "https://images.unsplash.com/photo-1619837567816-30f8694e19e3?auto=format&fit=crop&w=800&q=80",
    description:
      "Experience the magic of high mountain passes, beautiful lakes, and ancient monasteries.",
    duration: "7 Days / 6 Nights",
    highlights: [
      "Drive through Khardung La Pass (world's highest motorable road)",
      "Overnight stay at Pangong Tso Lake in luxury camps",
      "Double-humped Bactrian camel ride at Hunder Sand Dunes",
      "Visit Hemis, Thiksey & Shey Monasteries",
      "Magnetic Hill & confluence of Indus & Zanskar rivers",
    ],
    inclusions: [
      "Hotels in Leh & deluxe camps in Nubra & Pangong",
      "Breakfast & dinner daily",
      "All Inner Line Permits & wildlife fees",
      "Non-AC Xylo/Innova/Tempo Traveler as per mountain norms",
      "Oxygen cylinder in vehicle for high-altitude emergency",
    ],
    exclusions: [
      "Flight tickets to/from Leh",
      "Camel rides, ATV rides & rafting charges",
      "Personal snacks & laundry",
      "Medical insurance",
    ],
  }),
  enrich({
    title: "Chardham Tour",
    destination: "Uttarakhand Chardham",
    date: "27 SEP - 10 OCT",
    year: 2026,
    price: 38500,
    note: "Flight tickets extra",
    type: "Pilgrimage",
    category: "September - December 2026",
    image: "https://images.unsplash.com/photo-1730021618560-cdb6b81592c2?auto=format&fit=crop&w=800&q=80",
    description:
      "A sacred pilgrimage journey to Yamunotri, Gangotri, Kedarnath, and Badrinath.",
    duration: "14 Days / 13 Nights",
    highlights: [
      "Holy darshan at all 4 sacred Dham temples",
      "Ganga Aarti at Har Ki Pauri in Haridwar",
      "Overnight stay near Kedarnath Temple",
      "Holy dip in Tapt Kund & visit Mana Village",
      "Rishikesh Laxman Jhula & Ram Jhula exploration",
    ],
  }),
  enrich({
    title: "Andaman Tour",
    destination: "Andaman Islands",
    date: "29 SEP - 06 OCT",
    year: 2026,
    price: 35500,
    note: "Flight tickets extra",
    type: "Domestic",
    category: "September - December 2026",
    image: "https://images.unsplash.com/photo-1593202232429-549625b8660d?auto=format&fit=crop&w=800&q=80",
    description: "Relax on pristine white-sand beaches and explore beautiful coral reefs.",
    duration: "7 Days / 6 Nights",
    highlights: [
      "Light & Sound show at historic Cellular Jail",
      "Sunset at Radhanagar Beach",
      "Snorkeling & coral reef exploration at Elephant Beach",
      "Speedboat cruise to Havelock & Neil Islands",
      "Ross Island heritage walk & Chidiyatapu sunset point",
    ],
  }),
  enrich({
    title: "Bhutan Tour",
    destination: "Bhutan",
    date: "20 OCT - 27 OCT",
    year: 2026,
    price: 38500,
    note: "Flight tickets extra",
    type: "International",
    category: "September - December 2026",
    image: "https://images.unsplash.com/photo-1548777123-e216912df7d8?w=600&q=80",
    description:
      "Discover the land of happiness, stunning cliffside temples, and scenic valleys.",
    duration: "8 Days / 7 Nights",
  }),
  enrich({
    title: "Kerala Special",
    destination: "Kerala",
    date: "10 NOV - 20 NOV",
    year: 2026,
    price: 31500,
    note: "Train Tickets included",
    type: "Domestic",
    category: "September - December 2026",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
    description: "Explore green backwaters, pristine beaches, and beautiful hill stations.",
    duration: "11 Days / 10 Nights",
  }),
  enrich({
    title: "Rajsthan Special",
    destination: "Rajasthan",
    date: "10 NOV - 20 NOV",
    year: 2026,
    price: 31500,
    note: "Train Tickets included",
    type: "Domestic",
    category: "September - December 2026",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&q=80",
    description:
      "Immerse in the royal heritage, historic forts, and colorful culture of Rajasthan.",
    duration: "11 Days / 10 Nights",
  }),
  enrich({
    title: "Dubai Tour",
    destination: "Dubai",
    date: "12 NOV - 17 NOV",
    year: 2026,
    price: 95500,
    note: "All Inclusive",
    type: "International",
    category: "September - December 2026",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80",
    description:
      "Marvel at futuristic skyscrapers, desert safaris, and luxurious shopping destinations.",
    duration: "6 Days / 5 Nights",
    highlights: [
      "Desert safari with BBQ dinner",
      "Burj Khalifa & Dubai Mall visit",
      "Dhow cruise on Dubai Creek",
      "Palm Jumeirah photo stop",
      "City sightseeing with guide",
    ],
  }),
  enrich({
    title: "Thailand - Singapore Malaysia",
    destination: "Thailand, Singapore & Malaysia",
    date: "18 NOV - 28 NOV",
    year: 2026,
    price: 155500,
    note: "All Inclusive",
    type: "International",
    category: "September - December 2026",
    image: "https://images.unsplash.com/photo-1563833717765-00462801314e?w=600&q=80",
    description:
      "Enjoy a triple destination tropical adventure filled with fun, beaches, and city sights.",
    duration: "11 Days / 10 Nights",
  }),
  enrich({
    title: "Bali Tour",
    destination: "Bali",
    date: "25 NOV - 30 NOV",
    year: 2026,
    price: 95500,
    note: "All Inclusive",
    type: "International",
    category: "September - December 2026",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80",
    description: "Rejuvenate in beautiful temples, tropical beaches, and rich cultural heritage.",
    duration: "6 Days / 5 Nights",
  }),
  enrich({
    title: "Kerala Rameshwaram Madurai",
    destination: "Kerala, Rameshwaram & Madurai",
    date: "22 NOV - 02 DEC",
    year: 2026,
    price: 35500,
    note: "Including Train tickets",
    type: "Pilgrimage",
    category: "September - December 2026",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&q=80",
    description:
      "A spiritual tour covering the temples of Madurai, Rameshwaram, and Kerala backwaters.",
    duration: "11 Days / 10 Nights",
  }),
  enrich({
    title: "Assam - Meghalaya Arunachal",
    destination: "Assam, Meghalaya & Arunachal",
    date: "01 DEC - 12 DEC",
    year: 2026,
    price: 45500,
    note: "without Flight Tickets",
    type: "Domestic",
    category: "September - December 2026",
    image: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=600&q=80",
    description:
      "Experience double bridges, lush greenery, and scenic beauty of North-East India.",
    duration: "12 Days / 11 Nights",
  }),
  enrich({
    title: "Rajasthan Tour",
    destination: "Rajasthan",
    date: "10 DEC - 20 DEC",
    year: 2026,
    price: 29500,
    note: "Including Train Tickets",
    type: "Domestic",
    category: "September - December 2026",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&q=80",
    description: "Explore the historic palaces, culture, and architecture of Rajasthan.",
    duration: "11 Days / 10 Nights",
  }),
  enrich({
    title: "Kerala Rameshwaram Madurai",
    destination: "Kerala, Rameshwaram & Madurai",
    date: "02 JAN - 12 JAN",
    year: 2027,
    price: 35500,
    note: "Including 3 AC Train Tickets",
    type: "Pilgrimage",
    category: "New Year Tour",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    description: "Ring in the new year with a holy temple pilgrimage and backwater cruise.",
    duration: "11 Days / 10 Nights",
  }),
  enrich({
    title: "Rajasthan Tour",
    destination: "Rajasthan",
    date: "04 JAN - 14 JAN",
    year: 2027,
    price: 30500,
    note: "Including 3 AC Train Tickets",
    type: "Domestic",
    category: "New Year Tour",
    image: "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=600&q=80",
    description: "Celebrate the New Year exploring royal palaces and majestic deserts.",
    duration: "11 Days / 10 Nights",
  }),
  enrich({
    title: "Thailand - Singapore - Malaysia",
    destination: "Thailand, Singapore & Malaysia",
    date: "16 JAN - 26 JAN",
    year: 2027,
    price: 155500,
    note: "Including Flight, Visa Entry Tickets",
    type: "International",
    category: "New Year Tour",
    image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800&q=80",
    description: "Ring in the new year with an epic multi-country international holiday.",
    duration: "11 Days / 10 Nights",
  }),
  enrich({
    title: "Gujarat Tour",
    destination: "Gujarat",
    date: "21 JAN - 31 JAN",
    year: 2027,
    price: 30500,
    note: "Including 3 AC Train Tickets",
    type: "Domestic",
    category: "January - March 2027",
    image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=600&q=80",
    description:
      "Discover the land of Legends, from Dwarka Temple to the beautiful Rann of Kutch.",
    duration: "11 Days / 10 Nights",
  }),
  enrich({
    title: "Dubai Tour",
    destination: "Dubai",
    date: "25 JAN - 30 JAN",
    year: 2027,
    price: 95500,
    note: "Including Flight, Visa Entry Tickets",
    type: "International",
    category: "January - March 2027",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80",
    description: "Enjoy the ultimate winter desert escape in the world's most modern city.",
    duration: "6 Days / 5 Nights",
  }),
  enrich({
    title: "Rajasthan Tour",
    destination: "Rajasthan",
    date: "02 FEB - 12 FEB",
    year: 2027,
    price: 29500,
    note: "Including Flight, Visa Entry Tickets",
    type: "Domestic",
    category: "January - March 2027",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&q=80",
    description: "Experience Rajasthan's best winter weather with majestic palace visits.",
    duration: "11 Days / 10 Nights",
  }),
  enrich({
    title: "Andaman Tour",
    destination: "Andaman Islands",
    date: "07 FEB - 12 FEB",
    year: 2027,
    price: 35500,
    note: "Extra Flight Tickets",
    type: "Domestic",
    category: "January - March 2027",
    image: "https://images.unsplash.com/photo-1593202232429-549625b8660d?auto=format&fit=crop&w=800&q=80",
    description: "Enjoy a blissful tropical beach escape in the Andaman Islands.",
    duration: "6 Days / 5 Nights",
  }),
  enrich({
    title: "Kashmir Winter",
    destination: "Kashmir",
    date: "15 - 25 FEB",
    year: 2027,
    price: 32500,
    note: "Including Train Tickets",
    type: "Domestic",
    category: "January - March 2027",
    image: "https://images.unsplash.com/photo-1566228015668-4c45dbc4e2f5?w=600&q=80",
    description:
      "Experience paradise on Earth with snow-capped mountains and scenic Shikara rides.",
    duration: "11 Days / 10 Nights",
  }),
  enrich({
    title: "Kerala Rameshwaram Madurai Tour",
    destination: "Kerala, Rameshwaram & Madurai",
    date: "20 FEB - 02 MARCH",
    year: 2027,
    price: 35500,
    note: "Including 3 Ac Train Tickets",
    type: "Pilgrimage",
    category: "January - March 2027",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&q=80",
    description: "A beautiful south Indian temple run and backwater rejuvenation tour.",
    duration: "11 Days / 10 Nights",
  }),
  enrich({
    title: "Nepal Tour",
    destination: "Nepal",
    date: "01 MARCH - 10 MARCH",
    year: 2027,
    price: 35500,
    note: "Including 3 Ac Train Tickets",
    type: "International",
    category: "January - March 2027",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80",
    description:
      "Journey to the Himalayas and explore the rich culture of Kathmandu and Pokhara.",
    duration: "10 Days / 9 Nights",
  }),
  enrich({
    title: "Himachal Tour",
    destination: "Himachal Pradesh",
    date: "04 MARCH - 12 MARCH",
    year: 2027,
    price: 31500,
    note: "Including 3 Ac Train Tickets",
    type: "Domestic",
    category: "January - March 2027",
    image: "https://images.unsplash.com/photo-1677820915317-b5e5174c1f7a?auto=format&fit=crop&w=800&q=80",
    description: "Witness breathtaking snow-capped valleys, Manali, and Shimla hills.",
    duration: "9 Days / 8 Nights",
  }),
  enrich({
    title: "Dubai Tour",
    destination: "Dubai",
    date: "15 MARCH - 20 MARCH",
    year: 2027,
    price: 95500,
    note: "Including Flight, Visa Entry Tickets",
    type: "International",
    category: "January - March 2027",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80",
    description: "Enjoy shopping festivals, theme parks, and stunning beaches in Dubai.",
    duration: "6 Days / 5 Nights",
  }),
];
